###
# An ergonomic QWERTY variant for French:
#   - all accented chars can be made with the dead key and the 3Ã—10 main keys;
#   - all programming symbols can be made with AltGr and the 3Ã—10 main keys;
#   - on a full-size ISO keyboard, AltGr is handy but not required;
#   - suitable for all compact keyboards (40%, 42 keys, 34 keysâ€¦).
##

name = "Qwerty-Antznin"
name8 = "Qwerty-A"
locale = "fr"
variant = "antznin"
author = "Antonin Godard"
description = "French (Qwerty-Antznin, legacy)"
url = "https://github.com/fabi1cazenave/qwerty-lafayette"
geometry = "ERGO"
version = "0.9.0"

# To follow the 1DFH principle, all diacritics require a single dead key (1dk):
#   - 1dk + vowel         = grave accent / alt   (Ã , Ã¨, Ã¹, Ã§, Ã¯, Å“, Ã¦, Ã±, ÃŸ)
#   - 1dk + key left      = acute accent         (Ã©)
#   - 1dk + key below     = circumflex accent    (Ã¢, Ãª, Å·, Ã», Ã®, Ã´)
#   - 1dk + 1dk + vowel   = diaeresis            (Ã¤, Ã«, Ã¿, Ã¼, Ã¯, Ã¶)
# Other common typographic symbols have been added as well:
#   - 1dk + number        = symbol or quote sign (â€, â€œ, â€)
#   - 1dk + left index    = dash / underscore    (-, _, â€”, â€“)

base = '''
â•­â•Œâ•Œâ•Œâ•Œâ•Œâ”°â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”°â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”°â•Œâ•Œâ•Œâ•Œâ•Œâ”¬â•Œâ•Œâ•Œâ•Œâ•Œâ•®
â”† ~   â”ƒ ! â€ â”‚ @ â€œ â”‚ # â€ â”‚ $ Â¢ â”‚ % â€° â”ƒ ^   â”‚ &   â”‚ *   â”‚ (   â”‚ )   â”ƒ _   â”† + Â± â”†
â”† `   â”ƒ 1 Â¡ â”‚ 2 Â« â”‚ 3 Â» â”‚ 4 Â£ â”‚ 5 â‚¬ â”ƒ 6 Â¥ â”‚ 7 Â¤ â”‚ 8 Â§ â”‚ 9 Â¶ â”‚ 0 Â° â”ƒ - â€” â”† = â‰  â”†
â•°â•Œâ•Œâ•Œâ•Œâ•Œâ•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”¼â•Œâ•Œâ•Œâ•Œâ•Œâ”¤
Â·     â”ƒ Q   â”‚ W   â”‚ E   â”‚ R   â”‚ T   â”ƒ Y   â”‚ U   â”‚ I   â”‚ O   â”‚ P   â”ƒ {   â”† }   â”†
Â·     â”ƒ   Ã¦ â”‚   Ã© â”‚   Ã¨ â”‚     â”‚     â”ƒ     â”‚   Ã¹ â”‚   Ã¯ â”‚   Å“ â”‚     â”ƒ [   â”† ]   â”†
Â·     â” â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”¼â•Œâ•Œâ•Œâ•Œâ•Œâ”¤
Â·     â”ƒ A   â”‚ S   â”‚ D   â”‚ F Âª â”‚ G â€“ â”ƒ H   â”‚ J   â”‚ K   â”‚ L   â”‚**   â”ƒ "   â”† |   â”†
Â·     â”ƒ   Ã  â”‚   Ã« â”‚   Ãª â”‚   - â”‚   â€“ â”ƒ   Å· â”‚   Ã» â”‚   Ã® â”‚   Ã´ â”‚  *Â¨ â”ƒ '   â”† \   â”†
â•­â•Œâ•Œâ•Œâ•Œâ•Œâ•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”´â•Œâ•Œâ•Œâ•Œâ•Œâ•¯
â”† >   â”ƒ Z   â”‚ X   â”‚ C   â”‚ V _ â”‚ B â€” â”ƒ N   â”‚ M Âº â”‚ ; â€¢ â”‚ :   â”‚ ? Ã· â”ƒ           Â·
â”† <   â”ƒ   Ã¢ â”‚   Ã— â”‚   Ã§ â”‚   _ â”‚   â€” â”ƒ   Ã± â”‚   Âµ â”‚ , Â· â”‚ . â€¦ â”‚ / Â¿ â”ƒ           Â·
â•°â•Œâ•Œâ•Œâ•Œâ•Œâ”¸â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”¸â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”š Â· Â· Â· Â· Â· Â·
'''

# The AltGr layer focuses on the 28 programming symbols:
#   - 10 symbols over the numbers
#   - 2Ã—8 symbols on the extra pinky keys (base and shift layers)
#   - 2 symbols on the lower-right key (/?)
#   -> the 3Ã—10 alpha pad can fit these 28 symbols + ; and :
# Rationale:
#   - {()}<> signs on ASDFWE (= most comfortable positions)
#   - 1st row: most frequent chars from the number row ($%^&* below 45678)
#              (last-minute change: @^ are swapped to match Ergoâ€‘L 1.0)
#   - 2nd row: arithmetical signs
#   - 3rd row: shell / punctuation signs
# Efficiency:
#   - no symbols outside of the 3Ã—10 alpha pad
#   - no symbol that must be doubled is under a pinky
#   - most digrams seem comfortable to type

altgr = '''
â•­â•Œâ•Œâ•Œâ•Œâ•Œâ”°â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”°â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”¬â”€â”€â”€â”€â”€â”°â•Œâ•Œâ•Œâ•Œâ•Œâ”¬â•Œâ•Œâ•Œâ•Œâ•Œâ•®
â”†     â”ƒ   Â¹ â”‚   Â² â”‚   Â³ â”‚   â´ â”‚   âµ â”ƒ   â¶ â”‚   â· â”‚   â¸ â”‚   â¹ â”‚   â° â”ƒ     â”†     â”†
â”†     â”ƒ   â‚ â”‚   â‚‚ â”‚   â‚ƒ â”‚   â‚„ â”‚   â‚… â”ƒ   â‚† â”‚   â‚‡ â”‚   â‚ˆ â”‚   â‚‰ â”‚   â‚€ â”ƒ     â”†     â”†
â•°â•Œâ•Œâ•Œâ•Œâ•Œâ•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”¼â•Œâ•Œâ•Œâ•Œâ•Œâ”¤
Â·     â”ƒ  *^ â”‚   â‰¤ â”‚   â‰¥ â”‚  *Â¤ â”‚   â€° â”ƒ  *Ëš â”‚     â”‚   Ã— â”‚  *Â´ â”‚  *` â”ƒ     â”†     â”†
Â·     â”ƒ   ^ â”‚   < â”‚   > â”‚   $ â”‚   % â”ƒ   @ â”‚   & â”‚   * â”‚   ' â”‚   ` â”ƒ     â”†     â”†
Â·     â” â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”¼â•Œâ•Œâ•Œâ•Œâ•Œâ”¤
Â·     â”ƒ  *Ë‡ â”‚   â½ â”‚   â¾ â”‚  *Ë™ â”‚   â‰  â”ƒ   ğŸ¡ â”‚   ğŸ¡“ â”‚   ğŸ¡‘ â”‚   ğŸ¡’ â”‚  *â€ â”ƒ     â”†     â”†
Â·     â”ƒ   { â”‚   ( â”‚   ) â”‚   } â”‚   = â”ƒ   \ â”‚   + â”‚   - â”‚   / â”‚   " â”ƒ     â”†     â”†
â•­â•Œâ•Œâ•Œâ•Œâ•Œâ•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â”¼â”€â”€â”€â”€â”€â•‚â•Œâ•Œâ•Œâ•Œâ•Œâ”´â•Œâ•Œâ•Œâ•Œâ•Œâ•¯
â”†     â”ƒ  *~ â”‚  *, â”‚  *Ë› â”‚   â€“ â”‚     â”ƒ   Â¦ â”‚   Â¬ â”‚  *Â¸ â”‚   : â”‚  *Ë˜ â”ƒ           Â·
â”†     â”ƒ   ~ â”‚   [ â”‚   ] â”‚   _ â”‚   # â”ƒ   | â”‚   ! â”‚   ; â”‚   : â”‚   ? â”ƒ           Â·
â•°â•Œâ•Œâ•Œâ•Œâ•Œâ”¸â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”¸â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”´â”€â”€â”€â”€â”€â”š Â· Â· Â· Â· Â· Â·
'''

[spacebar]
shift       = "\u0020"  # SPACE
altgr       = "\u0020"  # SPACE
altgr_shift = "\u0020"  # SPACE
1dk         = "\u00a0"  # NO-BREAK SPACE
1dk_shift   = "\u00a0"  # NO-BREAK SPACE
